# Generated by Django 3.1.1 on 2020-10-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_num_prop'),
        ('contacts', '0002_auto_20201001_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seller',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent'),
            preserve_default=False,
        ),
    ]
