# Generated by Django 3.1.1 on 2020-10-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='seller',
        ),
    ]
