# Generated by Django 3.1.1 on 2020-10-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='property_id',
            field=models.IntegerField(),
        ),
    ]
