# Generated by Django 3.1.1 on 2020-09-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agent_num_prop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_status', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rating', models.IntegerField(max_length=5)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
            ],
        ),
    ]
