# Generated by Django 3.1.1 on 2020-09-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_num_prop'),
        ('routes', '0002_auto_20200925_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='testemonial',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testemonial',
            name='client',
            field=models.CharField(max_length=200),
        ),
    ]
