# Generated by Django 3.1.1 on 2020-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20200925_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemonial',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
