# Generated by Django 3.1.1 on 2020-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20200925_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemonial',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
