# Generated by Django 3.1.1 on 2020-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200925_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='built_year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='storey',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
